"""Wrap a single footprint in a minimal KiCad board for 3D (GLB) export.

kicad-cli pcb export glb renders the footprint the way KiCad itself would:
board slab, copper, soldermask, silkscreen, and the 3D component model with
the footprint's own offset/rotation applied — which is what fixes the
"model lying on its side" problem of viewing the raw STEP file.

The board template was generated by THIS KiCad version (pcbnew
CreateEmptyBoard), so it is guaranteed parseable.
"""
from __future__ import annotations

import re
from pathlib import Path

_TEMPLATE_PATH = Path(__file__).parent / "board_template.kicad_pcb"

# Coordinate-bearing tokens inside a footprint (excludes (xyz ...) used by 3D
# model offset/scale/rotate sections).
_COORD_RE = re.compile(r"\((?:at|start|end|xy|center|mid)\s+(-?\d+(?:\.\d+)?)\s+(-?\d+(?:\.\d+)?)")
_FOOTPRINT_HEADER_RE = re.compile(r'^(\(footprint\s+"[^"]+")')


def _bbox(footprint_text: str, margin: float = 1.5) -> tuple[float, float, float, float]:
    xs: list[float] = []
    ys: list[float] = []
    for m in _COORD_RE.finditer(footprint_text):
        xs.append(float(m.group(1)))
        ys.append(float(m.group(2)))
    if not xs:
        xs, ys = [0.0], [0.0]
    return min(xs) - margin, min(ys) - margin, max(xs) + margin, max(ys) + margin


def build_board_text(footprint_text: str) -> str:
    """Insert the footprint at the origin of the template board and draw an
    Edge.Cuts outline around its bounding box (a small board slab)."""
    template = _TEMPLATE_PATH.read_text(encoding="utf-8")

    fp = footprint_text.strip()
    # Board-embedded footprints carry a position; library files don't.
    fp = _FOOTPRINT_HEADER_RE.sub(r'\1\n\t(at 0 0)', fp, count=1)

    x1, y1, x2, y2 = _bbox(footprint_text)
    edges = "\n".join(
        f'\t(gr_line (start {sx} {sy}) (end {ex} {ey}) '
        f'(stroke (width 0.1) (type solid)) (layer "Edge.Cuts"))'
        for sx, sy, ex, ey in (
            (x1, y1, x2, y1),
            (x2, y1, x2, y2),
            (x2, y2, x1, y2),
            (x1, y2, x1, y1),
        )
    )

    body = "\t" + "\n\t".join(fp.splitlines()) + "\n" + edges + "\n"
    # insert before the final closing paren of (kicad_pcb ...)
    idx = template.rstrip().rfind(")")
    return template[:idx] + body + template[idx:]
